### ISSUE TITLE
Setting-up config file for validate_all

### ISSUE THREAD

**Issue by zakiF** [RenneLab/CnR-flow#4]
Hi, 

Many thanks for creating such a wonderful workflow for cut and run analysis. I am excited to try this workflow, this is my first attempt of using NextFlow, so perhaps I am missing some steps that are quite obvious. Any pointers would be most appreicated

I am encountering an error while running `nextflow run CnR-flow --mode validate_all`

<img width="941" alt="Screenshot 2021-06-15 at 14 16 12" src="https://user-images.githubusercontent.com/33129835/122059181-45125900-cde4-11eb-90cc-bef4179c7f06.png">

My nextflow.config file (.nextflow/assets/RenneLab/CnR-flow/nextflow.config) looks like below. 

```
params {
    // ------- Dependency Configuration --------
    // Configuration using conda is recommended for most systems.
    // Each dependency can only have one type of resource configured:
    // (Ex: bowtie2_module OR bowtie2_conda)

    // Dependency Configuration Using Anaconda
    // Miniconda Install Instructions:
    //     https://docs.conda.io/en/latest/miniconda.html
    //
    // -- External Conda Environments:
    facount_conda          = 'bioconda::ucsc-facount=366'
    bowtie2_conda          = 'bioconda::bowtie2=2.4.1'
    fastqc_conda           = 'bioconda::fastqc=0.11.9'
    trimmomatic_conda      = 'bioconda::trimmomatic=0.39'
    kseqtest_conda         = 'RenneLab::cutruntools-exec'
    bedtools_conda         = 'bioconda::bedtools=2.29.2'
    macs2_conda            = 'bioconda::macs2=2.2.6'
    R_conda                = 'r=3.6.0'
    seacr_conda            = "${params.R_conda} ${params.bedtools_conda}"
    samtools_conda         = 'bioconda::samtools=1.9'
    bedgraphtobigwig_conda = 'conda-forge::libpng conda-forge::libuuid conda-forge::mysql-connector-c conda-forge::openssl conda-forge::zlib bioconda::ucsc-bedgraphtobigwig=377'
```

My guess is I did not have bowtie2 installed in the conda? So I tried to install it with `conda install -c bioconda bowtie2=2.4.1`. Checking if the bowtie2 package is available with `conda list bowtie2` gave me the result ;

```
# packages in environment at /home/zfadlullah/anaconda3:
#
# Name                    Version                   Build  Channel
bowtie2                   2.4.1            py38he513fc3_0    bioconda

```

I think bowtie2 installed, so I am not sure why I am getting the error. 

Best,
Zaki

**Comment by dstrib** [comment]
Hi Zaki!
Thanks very much for the detailed report!
CnR-Flow is setup so that Nextflow creates a conda environment specifically for each step of the task, to avoid any conflicts between dependencies. Thus your intuition is right that it's a conda/bowtie2 problem, but installing Bowtie2 into your conda environment won't solve it in this case.

It appears the current Bowtie2 version is having issues with conda, as described here: https://github.com/BenLangmead/bowtie2/issues/336

Based on the suggested fix there, try changing the line in your config to:
bowtie2_conda          = 'bioconda::bowtie2=2.4.1 tbb=2020.2'

Let me know whether this works!
Dan

**Comment by zakiF** [comment]
Hi Dan, 

Many thanks for the helpful reply. The solution worked!

```

Dependencies Have been Validated, Results:
    [success, success, success, success, success, success, success, success, success, success, success, success]

Completed at: 16-Jun-2021 07:33:19
Duration    : 12m 50s
CPU hours   : (a few seconds)
Succeeded   : 12

```

Unfortunately, something else comes up now.  Running `nextflow run CnR-flow --mode dry_run` worked fine. However, when running 'nextflow run CnR-flow --mode run' another error comes up.

<img width="942" alt="Screenshot 2021-06-16 at 13 43 09" src="https://user-images.githubusercontent.com/33129835/122221599-540f0f00-cea9-11eb-8ba5-4fbd4041f491.png">

I tried re-running `nextflow run CnR-flow --mode run` as the error says a simple retry will work, however the HTTP error still remains. Would you prefer if I raise a sperate issue on github? 

Many thanks,
Zaki

**Comment by dstrib** [comment]
Hi Zaki,
Glad the first fixed worked! Continuing this issue is fine. Have you tried the run again recently? This appears to be a conda internet connection issue. If it's still the case, try copying that command mentioned in the error message and running it on your system. If that doesn't work, then it will be some problem with the way conda is setup on your system, or the way it accesses the internet perhaps?

**Comment by dstrib** [comment]
Closed for inactivity.
