### ISSUE TITLE
Running RenneLab/CnR-flow in mode validate: call process CnR_Validate (bowtie2) singularity image - string parsing error #127

### ISSUE THREAD

**Issue by mhriris** [RenneLab/CnR-flow#5]
Firstly, I’d like to thank you for this amazing work. I’m trying to apply the pipeline to analyze ChipSeq data. When attempting to run the pipeline in “validate mode” then calling the downloaded images of the system (docker images predefined in “nextflow.config”) with singularity containers, the 'bowtie2' image gives a container string parsing error with exit status (127). When I replaced the version with another updated one, I got the same error with “Samtool” then with “bedgraphtobigwig” and other docker images.

![Image1](https://user-images.githubusercontent.com/57253567/197822667-37b4e2c8-0088-48ae-89b0-28c37b2fc18d.png)
![Image2](https://user-images.githubusercontent.com/57253567/197822687-0a97f460-48ed-4b9a-a80c-08f467255fb1.png)

appreciate your time and effort
Many thanks.

System information: 
nextflow version : 22.04.5.5708
HPC
Local and Slurm executor were tested
Singularity: 3.8.7-1.el7

**Comment by dstrib** [comment]
Hi, thanks so much for your feedback and for your question!
What I would want to check may be happening is that Nextflow is not able to access singularity on your system. Based on Nextflow's asynchronous execution, the validate run mode selects an arbitrary program to test first, which is why it's sometimes reporting one program as having an error and sometimes reporting another, and it's giving Bash error 127 (Command not found). 
I suggest to try executing:

 `$ singularity run docker://quay.io/biocontainers/bowtie2:2.4.4--py38he5f0661_1`
 
 in your environment, and see if the singularity command can be found.
If that command is successful, try then running:

`$ bowtie2 --version`

Also, I notice in the screenshot you send that nextflow is failing to navigate to the working directory
` cd [path]/work/...`
Make sure that you have write access at this location, or specify a new location for the nextflow working directory.

**Comment by mhriris** [comment]
Thanks for the quick response!
For the first commands (singularity run and bowtie2 version) , I got this (Singularity seems work ):
![Image5](https://user-images.githubusercontent.com/57253567/198048527-d6daebdd-8798-4289-a8da-07378f6eafbe.png)
For the nextflow working directory, I ran the following commands :

export SINGULARITY_CACHEDIR=$HOME/scratch/cut_run/work
export NXF_SINGULARITY_CACHEDIR=$HOME/scratch/cut_run/work
export NXF_WORK =$HOME/scratch/cut_run/work

"cut_run" is my workspace location where I run -mode initiate and validate

And I'm still having the same error:
![Image3](https://user-images.githubusercontent.com/57253567/198050157-fd2d266f-eaed-4f3d-a1ed-6dac9f52645c.png)
![Image4](https://user-images.githubusercontent.com/57253567/198050169-26cb84a4-5d32-47cc-b234-56f973f6fc9a.png)

Thanks!

**Comment by dstrib** [comment]
Yes I agree those seem to be working fine.
Next try to copy and paste the "cd gpfs.../" command and see if you can execute it. If not, see what the first directory is that this works for (by removing one part of the right side one at a time).

Additionally, are you aware whether this working path has any symlinks in it? If so, try using the path without symlinks instead.

**Comment by mhriris** [comment]
I added "singularity.autoMounts = true" to nextflow.config inside the Singularity profile and now it works perfectly 

Thank you so much for your time and help!

**Comment by dstrib** [comment]
Excellent! Don't hesitate to reach out if you have any other questions.
